# Numpy Learning sheet

In [1]:
import numpy as np

***Defining Numpy array*** 

In [2]:
myarray=np.array([[1 , 2 , 3]] , np.int8)

In [3]:
myarray

array([[1, 2, 3]], dtype=int8)

In [4]:
myarray.shape  #getting array info where first represent no of rows and second no of columns

(1, 3)

***Creating numpy array using python converison***

In [5]:
listarr=np.array([[1 , 2 , 3] , [4 , 5 , 6] , [7 , 8 , 9]])

In [6]:
listarr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
listarr.dtype

dtype('int32')

In [8]:
listarr.shape

(3, 3)

In [9]:
listarr.size

9

***Defining array using different numpy funtions***

In [10]:
zeroes=np.zeros((2,2)) #using zeros function

In [11]:
zeroes

array([[0., 0.],
       [0., 0.]])

In [12]:
zeroes.shape

(2, 2)

In [13]:
zeroes.dtype

dtype('float64')

In [14]:
arr=np.arange(10)

In [15]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
lspace = np.linspace(1 , 5 , 5) #using linspace function

In [17]:
lspace

array([1., 2., 3., 4., 5.])

In [18]:
emp = np.empty((3 , 6))

In [19]:
emp

array([[1.37962049e-306, 1.24610791e-306, 1.11260959e-306,
        1.69109959e-306, 9.34603679e-307, 1.42419802e-306],
       [1.78019082e-306, 4.45061456e-308, 1.24612081e-306,
        1.37962049e-306, 9.34597567e-307, 1.29061821e-306],
       [1.78019625e-306, 1.11255866e-306, 8.90098127e-307,
        9.34609790e-307, 3.91792279e-317, 1.42410974e-306]])

In [20]:
emp_like = np.empty_like(lspace)

In [21]:
emp_like

array([1., 2., 3., 4., 5.])

In [22]:
identity = np.identity(3)

In [23]:
identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
arr = np.arange(9)

In [25]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [26]:
arr=arr.reshape(3 , 3)

In [27]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [28]:
arr.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [29]:
x = [[1 , 2 , 3] , [4 , 5 , 6] , [7 , 8 , 9]]

In [30]:
arr = np.array(x)

In [31]:
arr.sum(axis=0)

array([12, 15, 18])

In [32]:
arr.sum(axis=1)

array([ 6, 15, 24])

In [33]:
arr.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [34]:
arr.flat

In [35]:
for i in arr.flat:
    print(i)

1
2
3
4
5
6
7
8
9


In [36]:
arr.ndim     #number of dimensions

2

In [37]:
arr.nbytes

36

In [38]:
arr.argmax()    #gives the index with max element

8

In [39]:
one = np.array([1 , 3 , 2])

In [40]:
one.argsort()

array([0, 2, 1], dtype=int64)

In [41]:
one.argmin()

0

In [42]:
arr.argmax(axis=0)

array([2, 2, 2], dtype=int64)

In [43]:
arr.argmax(axis=1)

array([2, 2, 2], dtype=int64)

In [44]:
arr.argsort(axis=0)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]], dtype=int64)

In [45]:
arr.reshape(9)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
arr.sum()

45

In [47]:
arr.max()

9

In [48]:
arr.min()

1

In [49]:
arr.reshape(3 , 3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [50]:
np.where(arr>5)

(array([1, 2, 2, 2], dtype=int64), array([2, 0, 1, 2], dtype=int64))

In [51]:
np.count_nonzero(arr)

9

In [52]:
np.nonzero(arr)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [53]:
import sys

In [54]:
py_arr = [0 , 4 , 55 , 2]

In [55]:
np_arr = np.array(py_arr)

In [56]:
sys.getsizeof(1)*len(py_arr)

112

In [57]:
np_arr.itemsize*np_arr.size

16

In [58]:
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
